DFRobotMaqueenPlus.I2CInit()
basic.showIcon(IconNames.Heart)
music.playTone(262, music.beat(BeatFraction.Whole))
music.playTone(294, music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Whole))
music.playTone(294, music.beat(BeatFraction.Half))
music.playTone(262, music.beat(BeatFraction.Half))
music.playTone(294, music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Half))
music.playTone(262, music.beat(BeatFraction.Whole))
basic.pause(100)
DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.GREEN)
DFRobotMaqueenPlus.mototRun(Motors.ALL, Dir.CW, 100)
basic.pause(2000)
DFRobotMaqueenPlus.mototStop(Motors.ALL)
basic.pause(500)
DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.RED)
music.playTone(988, music.beat(BeatFraction.Whole))
DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 75)
DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 0)
basic.pause(1000)
DFRobotMaqueenPlus.mototStop(Motors.ALL)
basic.pause(10)
DFRobotMaqueenPlus.mototRun(Motors.ALL, Dir.CW, 100)
DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.GREEN)
basic.pause(2000)
DFRobotMaqueenPlus.mototStop(Motors.ALL)
basic.pause(500)
DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.RED)
music.playTone(988, music.beat(BeatFraction.Whole))
DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 75)
DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 0)
basic.pause(1000)
DFRobotMaqueenPlus.mototStop(Motors.ALL)
basic.pause(10)
DFRobotMaqueenPlus.mototRun(Motors.ALL, Dir.CW, 100)
DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.GREEN)
basic.pause(2000)
DFRobotMaqueenPlus.mototStop(Motors.ALL)
basic.pause(500)
DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.RED)
music.playTone(988, music.beat(BeatFraction.Whole))
DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 75)
DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 0)
basic.pause(1000)
DFRobotMaqueenPlus.mototStop(Motors.ALL)
basic.pause(10)
DFRobotMaqueenPlus.mototRun(Motors.ALL, Dir.CW, 100)
DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.GREEN)
basic.pause(2000)
DFRobotMaqueenPlus.mototStop(Motors.ALL)
basic.pause(500)
DFRobotMaqueenPlus.setRGBLight(RGBLight.RGBA, Color.RED)
music.playTone(988, music.beat(BeatFraction.Whole))
DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 75)
DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 0)
basic.pause(1000)
DFRobotMaqueenPlus.mototStop(Motors.ALL)
basic.pause(10)
